### ISSUE TITLE
CheckArousal  not working properly (MPreg can't be done properly)

### ISSUE THREAD

**Issue by Cyaran** [Ugre101/The-Essence-of-Gender#12]
Your male impregnation check of your CheckArousal function can't work.

The issue is located in line 31. You are comparing a string against an OR-concatinated literal list which is evaluated first.

Your code
`if (LastPressed == ("DoggyStyle" || "DoggyStyleAnal" || "Missionary")) `
evaluates always to
`if (LastPressed == "DoggyStyle") {`
because JavaScript picks always the first literal.

I implemented a fix for that. Check the attachment. At line 3 to 5 of my implementation,

 you can setup all those actions which will result in an impregnation. Maybe you should place ImpregAction in an global area so that variable isn't declared and initialized every function call.

[CheckArousal.zip](https://github.com/Ugre101/The-Essence-of-Gender/files/2533470/CheckArousal.zip)

**Comment by Ugre101** [comment]
Thanks will implement.
