### ISSUE TITLE
combat bug

### ISSUE THREAD

**Issue by figaroka** [Ugre101/The-Essence-of-Gender#134]
ver Merge pull request #133 from Ugre101/Ugre101-patch-3 
(the last one)
bug 1
in the combat page if you fight, your fight log dont clean it after fight and 3-4 fight later you dont see the buttons (too much log and the log push down the buttons).

bug 2
after fight, in the sex screen if you sex, both the rimjob and a stop sex buttons disappear the same time

sorry, but english is not my home language

**Comment by Ugre101** [comment]
Both should be fixed now, if it persist open a new report.
