### ISSUE TITLE
Big muscles are always fatty

### ISSUE THREAD

**Issue by AlexNipal** [Ugre101/The-Essence-of-Gender#14]
In Looks.js when we set "c" a character with no fat but big muscles does not reach line 201, it gets caught before because even a body with no fat matches "(who.Fat / who.Weight) * 100 <= 50". The description for healthy body should come first.

**Comment by Ugre101** [comment]
I see it now will fix it and will try to re balance saying that nobody knows  how a 160cm player with 30kg fat moves seems unrealistic.

**Comment by Ugre101** [comment]
Fixed it but the balance still need work.
